### ISSUE TITLE
선생님 네이버 바뀌어서 저게 안보입니다 ㅠㅠ

### ISSUE THREAD

**Issue by Tarrow9** [eungyeole/naver-realtime-keywords#1]
큰일났씁니다..!!!

**Comment by eungyeole** [comment]
@Tarrow9 이번주 내로 고쳐볼게용 ㅠㅠ

**Comment by Tarrow9** [comment]
고마워요 항상 감사합니다!

**Comment by eungyeole** [comment]
@Tarrow9 대응 작업 완료했고 구글 측과 웨일 측 심사 대기 중입니다.

**Comment by Tarrow9** [comment]
선생님 정말 대단하십니다 빠른 개선 적용 감사합니다!

**Comment by eungyeole** [comment]
크롬 반영 완료, 네이버 심사 중

**Comment by Tarrow9** [comment]
오! 이제 잘 보입니다 감사합니다~!~! 박스 이쁘게 만들어주셨네요!
