### ISSUE TITLE
Google Chrome 127.0.6533.89 버전 기준 확장프로그램 작동 하지 않습니다.

### ISSUE THREAD

**Issue by vkrnlrmrak1** [eungyeole/naver-realtime-keywords#5]
index.js line 44 에 있는 함수인
    document.addEventListener("DOMNodeInserted", initializeRealTimeWords);
가 문제를 일으키고 있는 것 같네요 
https://chromestatus.com/feature/5083947249172480
여기 보니까 그 함수가 예전에 지원 중단된 함수라나 뭐라나..
그래서 먹통 난 것 같습니다.
조속히 해결해주시면 합니다.

**Comment by eungyeole** [comment]
@vkrnlrmrak1 이슈 제보 감사합니다. 현재 심사 중이라 다음 주 중으로 해결될것 같아요

**Comment by eungyeole** [comment]
해결 완료
